name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Conveyor
        run: |-
          wget https://downloads.hydraulic.dev/conveyor/hydraulic-conveyor_5.0_amd64.deb
          sudo apt install ./hydraulic-conveyor_5.0_amd64.deb

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build releases for all platforms
        run: conveyor make site

      - name: Remove Jar
        run: rm build/libs/*.jar

      - name: Create Shadow Jar
        run: ./gradlew shadowJar

      - name: Rename Shadow Jar
        run: rename 's/-all.jar/.jar/' Komac*-all.jar

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
            output/*.appinstaller
            output/*.exe
            output/*.msix
            output/*.tar.gz
            output/*.zip
            output/*.deb
          generate_release_notes: true
